baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'portfolio'
[outputs]
  home = ["HTML"]
  section = ["HTML", "JSON"]

[mediaTypes]
  [mediaTypes."application/json"]
    suffixes = ["json"]

[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "index"